<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>kubernetes.output</string>
        <key>name</key>
        <string>kubernetes-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>token.info-token</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>string</string>
                    </dict>
                </dict>
                <key>match</key>
                <string>\[([^\r\n]*)(\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3})\]</string>
                <key>name</key>
                <string>kubernetes-output.name</string>
            </dict>
        </array>
    </dict>
</plist>