name: Development build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
        actions: read
        contents: read
        deployments: read
        packages: none
    env:
      NODE_OPTIONS: --max_old_space_size=4096
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: '22'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run compile
    - name: Lint extension source
      run: npm run lint
    - name: Smoke test (Linux)
      run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Smoke test (Mac, Windows)
      run: npm run test
      if: runner.os != 'Linux'
    - name: Package extension
      if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      run: |
        npm run package
        mkdir vsix
        mv *.vsix vsix
    - name: Archive extension
      if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: vsix
        path: vsix
